## __NUMPY LIBRARY - PYTHON__

### Key points : 

1. NumPy is the fundamental package for scientific computing in Python.


2. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and    matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


3. NumPy arrays have a fixed size at creation, Changing the size of an ndarray will create a new array and delete the original.


4. The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

***

In [25]:
import numpy as np

List vs Numpy - time taken - calculated using time package

In [26]:
from time import process_time

In [27]:
# time taken by list 

py_list=[i for i in range(50000)]
start_time=process_time()
py_list=[i+5 for i in py_list]
end_time=process_time()
print("time taken is : ",(end_time-start_time))

time taken is :  0.015625


In [32]:
# time taken by numpy array

np_array = np.array([i for i in range(50000000)])
start_t=process_time()
np_array += 5
end_t=process_time()
print(end_t-start_t)

0.078125


In [80]:
# n dimensional

n=np.array([(2,3,4),(6,7,8)],dtype='float')
print(n)
n.shape

#get specific row
print(n[0,:])

#get a specific column
print(n[:,0])

#get specific values
print(n[1:2:1])



nn=np.array([(45,67,89)], dtype=float)

[[2. 3. 4.]
 [6. 7. 8.]]
[2. 3. 4.]
[2. 6.]
[[6. 7. 8.]]


In [39]:
# create an array of zeros
arr=np.zeros((5,5))
print(arr)

# create an array of ones
ar=np.ones((3,3))
print(ar)

# create an array of specific values
a=np.full((5,4),7)
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [81]:
# create an identity matrix
x=np.eye(4)
print(x)

#or

y=np.identity(6)
print(y)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [70]:
# create a numpy array with random values
b=np.random.random((3,4))
print(b)

[[0.02580684 0.98362228 0.13559147 0.48578656]
 [0.29263324 0.95470632 0.06463468 0.65214276]
 [0.32811375 0.26758765 0.43927324 0.00533031]]


In [45]:
# random integer values array within a specific range
c=np.random.randint(4,66,33)
print(c)

[34 46 56  9 21 51 43 48 62 50 29 47 38 15 60 59 33 62 57 14 13 58 48 19
 27 11 32 55  9 65 58 25 51]


In [46]:
# getting a specific number of evenly spaced values in a range.
d = np.linspace(20,50,10)
print(d)

[20.         23.33333333 26.66666667 30.         33.33333333 36.66666667
 40.         43.33333333 46.66666667 50.        ]


In [88]:
# getting values from range with same diff btwn them
s=np.arange(20,30,5)
print(s)

# repeat method
z=np.repeat(s,4,axis=0)
print(z)

# Any other number (full_like)
np.full_like(a, 4)

[20 25]
[20 20 20 20 25 25 25 25]


array([4, 4, 4, 4, 4])

In [51]:
# list to numpy array conversion
li=[23,4,56,7,89]
a=np.asarray(li)
print(a)

[23  4 56  7 89]


***
### Analysing a numpy array
***

In [53]:
c=np.random.randint(30,80,(4,4)) # 4x4 array with random values in a specific range

#dimensions of array
print(c.shape)

#no. of dimensions
print(c.ndim) #its rows and columns so 2d

#no. of elements in an array
print(c.size)

#data type of values in the array
print(c.dtype)

(4, 4)
2
16
int32


***
### Mathematical operations on a numpy array
***

In [84]:
l1=[1,2,3,4,5]
l2=[6,7,8,9,11]

#add symbol = concatenate
print(l1+l2)

#for nd arrays
l3=np.random.randint(20,30,(3,3))
l4=np.random.randint(10,20,(3,3))

print(l3+l4)
print(l3-l4)
print(l3*l4)
print(l3/l4)


#cos
print(np.cos(l2))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 11]
[[40 43 34]
 [37 37 39]
 [36 36 43]]
[[18  9 14]
 [ 3 13  7]
 [ 4 12  5]]
[[319 442 240]
 [340 300 368]
 [320 288 456]]
[[2.63636364 1.52941176 2.4       ]
 [1.17647059 2.08333333 1.4375    ]
 [1.25       2.         1.26315789]]
[ 0.96017029  0.75390225 -0.14550003 -0.91113026  0.0044257 ]


In [87]:
l1=[1,2,3,4,5]
l2=[6,7,8,9,11]

#adding
print(np.add(l1,l2))

#subract
print(np.subtract(l1,l2))

#multiply
print(np.multiply(l1,l2))

#divide
print(np.divide(l1,l2))

#matrix multiplication
ll=np.ones((3,2))
lll=np.full((2,3),3)
print(ll," \n ",lll)
llll=np.matmul(ll,lll)
print(llll)

[ 7  9 11 13 16]
[-5 -5 -5 -5 -6]
[ 6 14 24 36 55]
[0.16666667 0.28571429 0.375      0.44444444 0.45454545]
[[1. 1.]
 [1. 1.]
 [1. 1.]]  
  [[3 3 3]
 [3 3 3]]
[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]


***
### Array manipulation
***

In [64]:
l3=np.random.randint(20,30,(3,3))

#transpose
t=np.transpose(l3)
print(t)

# here the transpose of l3 is stored into x
x=l3.T
print(x)

#reshaping an array
m=l3.reshape(1,9)
print(m)

[[22 28 24]
 [20 24 27]
 [21 23 27]]
[[22 28 24]
 [20 24 27]
 [21 23 27]]
[[22 20 21 28 24 23 24 27 27]]


In [89]:
# copying arrays - dont use = sign bcz we modify one array the other will also change
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


In [90]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

***
### Statistics
***

In [91]:
st = np.array([[1,2,3],[4,5,6]])
st

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
# min
np.min(st)

# max
np.max(st, axis=1)

# sum
np.sum(st, axis=0)

array([5, 7, 9])

***
### Loading data from file
***

In [99]:
filedata = np.genfromtxt('dt.txt', delimiter=',')
filedata = filedata.astype('int64')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [98]:
# Boolean masking and indexing

(~((filedata > 20) & (filedata < 90)))

array([[ True,  True, False,  True,  True, False,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True, False,  True, False,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True, False, False,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])